Batch/urls.py
from django.contrib import admin
from django.urls import path
from Batch.views import *

app_name = "batch"

urlpatterns = [
    path('', BatchIndex.as_view(), name='batch_list'),
    path('create/', BatchCreate.as_view(), name='batch_create'),
]

XTrace/urls.py
from django.contrib import admin
from django.urls import include, path
urlpatterns = [
    path('admin/', admin.site.urls),
    # web
    path('web/batch/', include('Batch.urls', namespace='batch')),
    path('web/equipment/', include('Equipment.urls', namespace='equipment')),
    # API
]

Batch/models.py
from auditlog.registry import auditlog
from django.db import models
from django.urls import reverse

class Batch(models.Model):
    batch_number = models.CharField(max_length=100, unique=True, verbose_name="Batch Number")
    product = models.ForeignKey('Product.Product', on_delete=models.CASCADE, related_name='batches', verbose_name="Product")
    manufactured_at = models.DateField(verbose_name="Manufactured At")
    expiry_date = models.DateField(verbose_name="Expiry Date")
    quantity = models.PositiveIntegerField(verbose_name="Quantity")
    sampled_quantity = models.PositiveIntegerField(verbose_name="Sampled Quantity")
    order_number = models.CharField(max_length=100, verbose_name="Order Number")
    batch_description = models.TextField(blank=True, null=True, verbose_name="Batch Description")
    
    serial_pool = models.ForeignKey(
        'SerialNumberPool.SerialNumberPool', 
        on_delete=models.PROTECT,
        related_name='batches_used_in',
        verbose_name="Serial Number Configuration Pool"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

auditlog.register(Batch)

Batch/views.py
from django.shortcuts import render
from django.views.generic import *
from Batch.models import Batch
from SerialNumberPool.models import SerialNumberPool
# Create your views here.

class BatchIndex(ListView):
    model = Batch
    template_name = 'index.html'
    context_object_name = 'batches'

class BatchDetails(DetailView):
    model = Batch
    template_name = 'details.html'
    context_object_name = 'batch'

class BatchUpdate(UpdateView):
    model = Batch
    template_name = 'update.html'
    success_url = '/batches/'
    fields = ['batch_number', 'manufactured_at', 'expiry_date', 'quantity', 'sampled_quantity', 'order_number', 'batch_description']

class BatchCreate(CreateView):
    template_name = 'create.html'
    model = Batch
    success_url = '/batches/'
    fields = ['batch_number', 'product', 'manufactured_at', 'expiry_date', 'quantity', 'sampled_quantity', 'order_number', 'batch_description']

    def form_valid(self, form):
        serial_pool = SerialNumberPool.manager.create_pool_for_product(
            total_count=form.instance.quantity,
            user=self.request.user
        )
        return super().form_valid(form)

Batch/templates/create.html
{% extends "base.html" %}
{% load static %}

{% block title %}Create{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h2>Create New Item</h2>
            <form method="post" action="{% url 'batch:batch_create' %}">
                {% csrf_token %}
                <div class="mb-3">
                    {{ form.as_p }}
                </div>
                <button type="submit" class="btn btn-primary">Create</button>
                <a href="{% url 'batch:batch_list' %}" class="btn btn-secondary">Cancel</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

Batch/templates/index.html
{% extends 'base.html' %}
{% block content %}
<h1>batch</h1>
<ul>
    {% for batch in batches %}
    <li>
        <a href="{% url 'batch:batch_details' batch.id %}">{{ batch.name }}</a>
    </li>
    {% empty %}
    <li>No batch batch available.</li>
    {% endfor %}
</ul>
<a href="{% url 'batch:batch_create' %}">Create New batch</a>
{% endblock %}